/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lineclient;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author M4lZK
 */
public class GroupChat extends javax.swing.JFrame {

    /**
     * Creates new form GroupChat
     */
    String username,gid;
    Socket sock;
    boolean isConnect;
    BufferedReader reader;
    PrintWriter writer;
    public GroupChat() {
        initComponents();
    }
    
    public GroupChat(String username,String gid){
        this.username = username;
        this.gid = gid;
        this.isConnect=true;
        initComponents();
       // getUnread();
         try 
            {
                sock = new Socket("localhost", 2222);
                InputStreamReader streamreader = new InputStreamReader(sock.getInputStream());
                reader = new BufferedReader(streamreader);
                writer = new PrintWriter(sock.getOutputStream());
            } 
            catch (Exception ex) 
            {
             
            }
            
           ListenThread();
    }
    
   public void ListenThread() 
    {
         Thread IncomingReader = new Thread(new IncomingReader());
         IncomingReader.start();
    }
    
    public void reconnectTo2(){
         try 
            {   sock.close();
                sock = new Socket("localhost", 1111);
                InputStreamReader streamreader = new InputStreamReader(sock.getInputStream());
                reader = new BufferedReader(streamreader);
                writer = new PrintWriter(sock.getOutputStream());
            } 
            catch (Exception ex) 
            {
             
            }
            
           ListenThread();
    }

    public class IncomingReader implements Runnable
    {
        @Override
        public void run() 
        {
            String[] data;
            String stream, chat = "Chat";
            if(!isConnect) return;
            try 
            {
                while ((stream = reader.readLine()) != null) 
                {
                     data = stream.split(":");
             
                     if (data[1].equals(chat)&&data[3].equals((gid))) 
                     {
                         
                        jTextArea1.append(data[0] + ": "+ "("+data[4]+":"+data[5]+":"+data[6]+") : " + data[2] +"\n");
                         jTextArea1.setCaretPosition( jTextArea1.getDocument().getLength());
                     }
                     else if (data[0].equals("ServerDown")){
          reconnectTo2();
        }
                     
               
                }
           }catch(Exception ex) { }
        }
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gID_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TextField = new javax.swing.JTextField();
        send_Button = new javax.swing.JButton();
        cID_text = new javax.swing.JLabel();
        invite = new javax.swing.JButton();
        exit_GroupChat = new javax.swing.JButton();
        leave_group = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gID_text.setText("GroupID :");
        gID_text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gID_textPropertyChange(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });

        send_Button.setText("send");
        send_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_ButtonActionPerformed(evt);
            }
        });

        cID_text.setText("myID :");
        cID_text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cID_textPropertyChange(evt);
            }
        });

        invite.setText("invite");
        invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteActionPerformed(evt);
            }
        });

        exit_GroupChat.setText("exit");
        exit_GroupChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_GroupChatActionPerformed(evt);
            }
        });

        leave_group.setText("leave");
        leave_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leave_groupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextField)
                                .addGap(18, 18, 18)
                                .addComponent(send_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gID_text)
                        .addGap(119, 119, 119)
                        .addComponent(cID_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(invite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit_GroupChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leave_group, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gID_text)
                    .addComponent(cID_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invite)
                    .addComponent(exit_GroupChat)
                    .addComponent(leave_group))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_ButtonActionPerformed
        // TODO add your handling code here:
        if(!isConnect) return;
        String nothing = "";
        if ((TextField.getText()).equals(nothing)) {
            TextField.setText("");
            TextField.requestFocus();
        } else {
            try {
               String targetID = gid;
               writer.println(username + ":" + TextField.getText() + ":" + "Chat" + ":" +  targetID);
               writer.flush(); // flushes the buffer
            } catch (Exception ex) {
               jTextArea1.append("Message was not sent. \n");
            }
            TextField.setText("");
            TextField.requestFocus();
        }

        TextField.setText("");
        TextField.requestFocus();
    }//GEN-LAST:event_send_ButtonActionPerformed

    private void gID_textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gID_textPropertyChange
      gID_text.setText("GroupID : "+gid);  // TODO add your handling code here:
    }//GEN-LAST:event_gID_textPropertyChange

    private void cID_textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cID_textPropertyChange
       cID_text.setText("myID : "+username);   // TODO add your handling code here:
    }//GEN-LAST:event_cID_textPropertyChange

    private void inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteActionPerformed
       if(!isConnect) return;
       String cid;
       cid = JOptionPane.showInputDialog("Please Client ID");
       try{
                int count2 = Integer.parseInt(cid);
              
                writer.println(username + ":" + this.gid +":"+ "CG" + ":" + 3 + ":" + count2);
                writer.flush();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please insert number", "WRONG CLIENTID", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_inviteActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void exit_GroupChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_GroupChatActionPerformed
        // TODO add your handling code here:
         jTextArea1.setText("");
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_exit_GroupChatActionPerformed

    private void leave_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leave_groupActionPerformed
        String bye = (username + ": :Disconnect" );
        try
        {
            writer.println(username + ":" +username+" leave the group" + ":" + "leave" + ":" +  gid);
            writer.flush();
            jTextArea1.setText("");
            this.dispose();
         /*---delete user form server---  
            writer.println(bye); 
            writer.flush();
           sock.close();
        */
            
        } 
        catch(Exception ex) {
            jTextArea1.append("Failed to leave. \n");
        }
        
    }//GEN-LAST:event_leave_groupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupChat().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JLabel cID_text;
    private javax.swing.JButton exit_GroupChat;
    private javax.swing.JLabel gID_text;
    private javax.swing.JButton invite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton leave_group;
    private javax.swing.JButton send_Button;
    // End of variables declaration//GEN-END:variables
}
